### ISSUE TITLE
Example simulation error

### ISSUE THREAD

**Issue by hjw19** [modelica/PowerSystems#14]
Error occurs when i simulate 'PowerSystems/Examples/GenerationAC3ph/Turbin generator' example file.

Error message is as follows:

======================================================
division by zero at time 0, (a=45160) / (b=0), where divisor b expression is: generator.c.omega_nom

Debug more

simulation terminated by an assertion at initialization

Process crashed.

Simulation process failed. Exited with code -1.

=====================================================

Version of modelica is 'OpenModelica-v1.9.4-dev.beta1-85'
What's the problem? 

Thank you for reading.

**Comment by tbeu** [comment]
I guess this issue rather should go to the OMC developers, e.g. @rfranke @sjoelund

**Comment by sjoelund** [comment]
For OMC issues go to trac.openmodelica.org/OpenModelica

**Comment by rfranke** [comment]
PowerSystems, like many other Modelica libraries, uses Dymola as the reference tool.

OpenModelica has nightly tests for the PowerSystems library. You see that so far only around 77% of the models compile and 69% simulate:
   https://test.openmodelica.org/libraries/PowerSystems/BuildModelRecursive.html

There are also some active support tickets. Search for PowerSystems under
   https://trac.openmodelica.org/OpenModelica/report
