### ISSUE TITLE
HTML conventions are not followed for h3

### ISSUE THREAD

**Issue by tbeu** [modelica/PowerSystems#16]
Modelica (Standard Library) convention: `In the HTML documentation of any Modelica library, the headings <h1>, <h2> and <h3> should not be used, because they are utilized by the automatically generated documentation.`

See corresponding MSL ticket https://trac.modelica.org/Modelica/ticket/1746. Since PowerSystems depends on the MSL it might be useful to follow its conventions.

**Comment by rfranke** [comment]
Fixed in 34e4df5
