### ISSUE TITLE
Can't change AC1ph_DC ACvoltage source fType_par parameter in the dialog

### ISSUE THREAD

**Issue by Sup3rGeo** [modelica/PowerSystems#17]
Hi,

When I try to use the source _ACvoltage_ from the _AC1ph_DC_ blocks, I never get to set the _fType_par_ to _false_ (the dialog shows it grayed, read-only) regardless of the setting of _fType_sys_ and _scType_par_ parameters (that can be changed).

Therefore I can't get to use an ACvoltage with variable frequency in my models.

Thank you.

**Comment by dietmarw** [comment]
Hi,

I shortly tested it with the latest version from master and the last 0.4.0 release and it works fine in Dymola2017:
![screenshot from 2016-07-21 09-10-46](https://cloud.githubusercontent.com/assets/9332/17014130/2636ca2e-4f23-11e6-9177-7c3e89b8ecdb.png)
 but **not** in OMedit. So this is basically an issue of the OpenModelica tool (which I assume you used) and you should report it there: https://trac.openmodelica.org/OpenModelica/newticket
