### ISSUE TITLE
Unit of measure

### ISSUE THREAD

**Issue by ceraolo** [modelica/PowerSystems#21]
In PowerSystems.Control.Modulation.Partials.PWMasynBase

I read this:
  parameter SI.Frequency dtmin(min=Modelica.Constants.eps,max=0.1*del_t)=1e-6
      "minimal time between on/off";

It should be a Time, not a frequency.

**Comment by rfranke** [comment]
Thanks for the hint! See: 5e99d0224f5c375d3ec3b13dbec630bd7d5a8157
