### ISSUE TITLE
Two issues with AC3ph.Load

### ISSUE THREAD

**Issue by ceraolo** [modelica/PowerSystems#24]
Consider Examples.Spot.AC3Ph.Load. 
In it, meter can show quantities in V or p.u.
Try to execute the model with meter's puUnits  first true, then false.
Is its observed that the results show no difference! After some analysis it results to be true, dince the applied voltage is 1V, and the meter's V_nom is 1 V.

I propose to reformulate the example so that when SIUnits are used different values are shown (e.g. 100V).
**So the usage one Volt in this example is the first issue.**

When trying to change the model, I found it confusing having for load V_nom do be specified in kV, and S_nom in VA. Either use V and VA, or kV or MVA.
**So, the choice of units of measure for load nominal voltage and nominal power is the second issue.**

**Comment by rfranke** [comment]
See #22 for the p.u. issue. The unit of S_nom was changed to MVA with commit d20d3dcbb9677b3975f509afd8998a46a4776332 (Introduce own package for used SI units).
