### ISSUE TITLE
how do I open this package under modellica?

### ISSUE THREAD

**Issue by Sinan81** [modelica/PowerSystems#35]
Hi, I am an absolutely new to this software, and wanted to give it a try. I am wondering if someone can tell me how to open, or get started with this package. I have openmodellica installed in my OS.

**Comment by raulrpearson** [comment]
@Sinan81, I think it should be available in OMEdit through `File >> Systems Libraries`. I've checked in my OpenModelica installation (v1.12.0) and it includes what seems to be the latest version of this library.

If that weren't the case, you can always download the latest version of the library from GitHub by [cloning the repository](https://help.github.com/articles/cloning-a-repository/) or downloading a [zip of the latest commit](https://github.com/modelica/PowerSystems/archive/master.zip).

**Comment by Sinan81** [comment]
Thanks. I will give it a try within few days and get back to you.
