### ISSUE TITLE
Please release 0.6.1 with latest fixes

### ISSUE THREAD

**Issue by casella** [modelica/PowerSystems#40]
@rfranke I am monitoring the [status of PowerSystems](https://libraries.openmodelica.org/branches/newInst/PowerSystems/PowerSystems.html) with the new OMC front end. There are many failures due to missing 'each' that were corrected in the master version with some PRs, but unless you make a 0.6.1 (or 0.7.0) release, Hudson won't take them into consideration, because it runs on the last released version.

Thanks!

**Comment by rfranke** [comment]
Just released version 1.0.0.

**Comment by casella** [comment]
Great!

**Comment by dietmarw** [comment]
Just out of interest, is 1.0.0 no longer compatible with 0.6.0 or what was the reason for the major version bump?

**Comment by beutlich** [comment]
We should have also updated the license (from ModelicaLicense 2 to 3-Clause BSD) for a proper v1.0.0 (which came out of sudden).
