### ISSUE TITLE
Please update modelica/PowerSystems to 1.0.0

### ISSUE THREAD

**Issue by casella** [modelica/PowerSystems#41]
The default [link](https://github.com/modelica/PowerSystems) for the Power System library still points to the 0.6.0 release. Please update it to 1.0.0, so that people and the OpenModelica Hudson CI use the latest released version instead of the old one.

When done, please close [#5242](https://trac.openmodelica.org/OpenModelica/ticket/5242) on the OpenModelica trac.

**Comment by rfranke** [comment]
Updated download link

**Comment by casella** [comment]
@rfranke the problem is not solved, if you check https://github.com/modelica/PowerSystems/tree/release, it is still showing 0.6.0

Please make sure https://github.com/modelica/PowerSystems/tree/release points to 1.0.0, as the OpenModelica CI points to that, and I would like to have updated coverage results for the new front-end ASAP.

Thanks!

**Comment by casella** [comment]
When you are done, please close [#5242](https://trac.openmodelica.org/OpenModelica/ticket/5242) on the OpenModelica trac. Thanks!
